-- ═══════════════════════════════════════════════════════════════════════════
-- Farooq & Co Traders ERP — server database (MariaDB 11.x)
-- GENERATED by scripts/gen-mariadb-schema.mjs — do not edit by hand; edit the spec there.
-- Target database: u943531942_facotraders (business data). Logins live in the separate
-- u943531942_erpauth database (auth-schema.sql) and are never mixed with this.
--
-- Each table = one former IndexedDB store. `doc` is the app's complete record (JSON);
-- the typed columns are generated from it by the database, so they cannot drift.
-- `rev` is bumped on every write (optimistic concurrency for several users at once).
-- ═══════════════════════════════════════════════════════════════════════════
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `meta` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = k',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_meta` CHECK (JSON_VALID(`doc`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sequences` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = k',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `kind` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.kind'),'')) STORED,
  `year` DECIMAL(20,0) GENERATED ALWAYS AS (CAST(NULLIF(JSON_VALUE(`doc`,'$.year'),'') AS DECIMAL(20,0))) STORED,
  `n` DECIMAL(20,0) GENERATED ALWAYS AS (CAST(NULLIF(JSON_VALUE(`doc`,'$.n'),'') AS DECIMAL(20,0))) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_sequences` CHECK (JSON_VALID(`doc`)),
  KEY `ix_kind` (`kind`),
  KEY `ix_year` (`year`),
  KEY `ix_n` (`n`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `business` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_business` CHECK (JSON_VALID(`doc`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `warehouses` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `name` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.name'),'')) STORED,
  `active` TINYINT(1) GENERATED ALWAYS AS ((JSON_VALUE(`doc`,'$.active') IN ('true','1'))) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_warehouses` CHECK (JSON_VALID(`doc`)),
  KEY `ix_name` (`name`),
  KEY `ix_active` (`active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `regions` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `active` TINYINT(1) GENERATED ALWAYS AS ((JSON_VALUE(`doc`,'$.active') IN ('true','1'))) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_regions` CHECK (JSON_VALID(`doc`)),
  KEY `ix_active` (`active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `products` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `cat` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.cat'),'')) STORED,
  `category` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.category'),'')) STORED,
  `sku` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.sku'),'')) STORED,
  `barcode` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.barcode'),'')) STORED,
  `active` TINYINT(1) GENERATED ALWAYS AS ((JSON_VALUE(`doc`,'$.active') IN ('true','1'))) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_products` CHECK (JSON_VALID(`doc`)),
  KEY `ix_cat` (`cat`),
  KEY `ix_category` (`category`),
  KEY `ix_sku` (`sku`),
  KEY `ix_barcode` (`barcode`),
  KEY `ix_active` (`active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `customers` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `region` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.region'),'')) STORED,
  `legacy_code` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.legacyCode'),'')) STORED,
  `sh` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.sh'),'')) STORED,
  `ph` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.ph'),'')) STORED,
  `active` TINYINT(1) GENERATED ALWAYS AS ((JSON_VALUE(`doc`,'$.active') IN ('true','1'))) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_customers` CHECK (JSON_VALID(`doc`)),
  KEY `ix_region` (`region`),
  KEY `ix_legacy_code` (`legacy_code`),
  KEY `ix_sh` (`sh`),
  KEY `ix_ph` (`ph`),
  KEY `ix_active` (`active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `suppliers` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `legacy_code` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.legacyCode'),'')) STORED,
  `co` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.co'),'')) STORED,
  `active` TINYINT(1) GENERATED ALWAYS AS ((JSON_VALUE(`doc`,'$.active') IN ('true','1'))) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_suppliers` CHECK (JSON_VALID(`doc`)),
  KEY `ix_legacy_code` (`legacy_code`),
  KEY `ix_co` (`co`),
  KEY `ix_active` (`active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `inventory` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `product_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.productId'),'')) STORED,
  `warehouse_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.warehouseId'),'')) STORED,
  `qty` DECIMAL(20,3) GENERATED ALWAYS AS (CAST(NULLIF(JSON_VALUE(`doc`,'$.qty'),'') AS DECIMAL(20,3))) STORED,
  `damaged_qty` DECIMAL(20,3) GENERATED ALWAYS AS (CAST(NULLIF(JSON_VALUE(`doc`,'$.damagedQty'),'') AS DECIMAL(20,3))) STORED,
  `avg_cost_p` DECIMAL(20,0) GENERATED ALWAYS AS (CAST(NULLIF(JSON_VALUE(`doc`,'$.avgCostP'),'') AS DECIMAL(20,0))) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_inventory` CHECK (JSON_VALID(`doc`)),
  KEY `ix_product_id` (`product_id`),
  KEY `ix_warehouse_id` (`warehouse_id`),
  KEY `ix_qty` (`qty`),
  KEY `ix_damaged_qty` (`damaged_qty`),
  KEY `ix_avg_cost_p` (`avg_cost_p`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `stock_movements` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `product_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.productId'),'')) STORED,
  `warehouse_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.warehouseId'),'')) STORED,
  `created_at` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.createdAt'),'')) STORED,
  `date` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.date'),'')) STORED,
  `ref` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.ref'),'')) STORED,
  `kind` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.kind'),'')) STORED,
  `qty_delta` DECIMAL(20,3) GENERATED ALWAYS AS (CAST(NULLIF(JSON_VALUE(`doc`,'$.qtyDelta'),'') AS DECIMAL(20,3))) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_stock_movements` CHECK (JSON_VALID(`doc`)),
  KEY `ix_product_id` (`product_id`),
  KEY `ix_warehouse_id` (`warehouse_id`),
  KEY `ix_created_at` (`created_at`),
  KEY `ix_date` (`date`),
  KEY `ix_ref` (`ref`),
  KEY `ix_kind` (`kind`),
  KEY `ix_qty_delta` (`qty_delta`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `invoices` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `invoice_number` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.invoiceNumber'),'')) STORED,
  `customer_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.customerId'),'')) STORED,
  `warehouse_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.warehouseId'),'')) STORED,
  `invoice_date` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.invoiceDate'),'')) STORED,
  `status` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.status'),'')) STORED,
  `order_number` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.orderNumber'),'')) STORED,
  `payment_status` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.paymentStatus'),'')) STORED,
  `grand_total` DECIMAL(20,0) GENERATED ALWAYS AS (CAST(NULLIF(JSON_VALUE(`doc`,'$.grandTotal'),'') AS DECIMAL(20,0))) STORED,
  `paid_amount` DECIMAL(20,0) GENERATED ALWAYS AS (CAST(NULLIF(JSON_VALUE(`doc`,'$.paidAmount'),'') AS DECIMAL(20,0))) STORED,
  `balance_amount` DECIMAL(20,0) GENERATED ALWAYS AS (CAST(NULLIF(JSON_VALUE(`doc`,'$.balanceAmount'),'') AS DECIMAL(20,0))) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_invoices` CHECK (JSON_VALID(`doc`)),
  UNIQUE KEY `uq_invoice_number` (`invoice_number`),
  KEY `ix_customer_id` (`customer_id`),
  KEY `ix_warehouse_id` (`warehouse_id`),
  KEY `ix_invoice_date` (`invoice_date`),
  KEY `ix_status` (`status`),
  KEY `ix_order_number` (`order_number`),
  KEY `ix_payment_status` (`payment_status`),
  KEY `ix_grand_total` (`grand_total`),
  KEY `ix_paid_amount` (`paid_amount`),
  KEY `ix_balance_amount` (`balance_amount`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `invoice_items` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `invoice_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.invoiceId'),'')) STORED,
  `product_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.productId'),'')) STORED,
  `quantity` DECIMAL(20,3) GENERATED ALWAYS AS (CAST(NULLIF(JSON_VALUE(`doc`,'$.quantity'),'') AS DECIMAL(20,3))) STORED,
  `line_total` DECIMAL(20,0) GENERATED ALWAYS AS (CAST(NULLIF(JSON_VALUE(`doc`,'$.lineTotal'),'') AS DECIMAL(20,0))) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_invoice_items` CHECK (JSON_VALID(`doc`)),
  KEY `ix_invoice_id` (`invoice_id`),
  KEY `ix_product_id` (`product_id`),
  KEY `ix_quantity` (`quantity`),
  KEY `ix_line_total` (`line_total`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `purchases` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `purchase_number` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.purchaseNumber'),'')) STORED,
  `supplier_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.supplierId'),'')) STORED,
  `warehouse_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.warehouseId'),'')) STORED,
  `purchase_date` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.purchaseDate'),'')) STORED,
  `status` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.status'),'')) STORED,
  `grand_total` DECIMAL(20,0) GENERATED ALWAYS AS (CAST(NULLIF(JSON_VALUE(`doc`,'$.grandTotal'),'') AS DECIMAL(20,0))) STORED,
  `paid_amount` DECIMAL(20,0) GENERATED ALWAYS AS (CAST(NULLIF(JSON_VALUE(`doc`,'$.paidAmount'),'') AS DECIMAL(20,0))) STORED,
  `balance_amount` DECIMAL(20,0) GENERATED ALWAYS AS (CAST(NULLIF(JSON_VALUE(`doc`,'$.balanceAmount'),'') AS DECIMAL(20,0))) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_purchases` CHECK (JSON_VALID(`doc`)),
  UNIQUE KEY `uq_purchase_number` (`purchase_number`),
  KEY `ix_supplier_id` (`supplier_id`),
  KEY `ix_warehouse_id` (`warehouse_id`),
  KEY `ix_purchase_date` (`purchase_date`),
  KEY `ix_status` (`status`),
  KEY `ix_grand_total` (`grand_total`),
  KEY `ix_paid_amount` (`paid_amount`),
  KEY `ix_balance_amount` (`balance_amount`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `purchase_items` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `purchase_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.purchaseId'),'')) STORED,
  `product_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.productId'),'')) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_purchase_items` CHECK (JSON_VALID(`doc`)),
  KEY `ix_purchase_id` (`purchase_id`),
  KEY `ix_product_id` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `payments` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `receipt_number` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.receiptNumber'),'')) STORED,
  `party_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.partyId'),'')) STORED,
  `party_type` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.partyType'),'')) STORED,
  `payment_date` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.paymentDate'),'')) STORED,
  `direction` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.direction'),'')) STORED,
  `status` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.status'),'')) STORED,
  `amount` DECIMAL(20,0) GENERATED ALWAYS AS (CAST(NULLIF(JSON_VALUE(`doc`,'$.amount'),'') AS DECIMAL(20,0))) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_payments` CHECK (JSON_VALID(`doc`)),
  UNIQUE KEY `uq_receipt_number` (`receipt_number`),
  KEY `ix_party_id` (`party_id`),
  KEY `ix_party_type` (`party_type`),
  KEY `ix_payment_date` (`payment_date`),
  KEY `ix_direction` (`direction`),
  KEY `ix_status` (`status`),
  KEY `ix_amount` (`amount`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `payment_allocations` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `payment_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.paymentId'),'')) STORED,
  `invoice_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.invoiceId'),'')) STORED,
  `purchase_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.purchaseId'),'')) STORED,
  `amount` DECIMAL(20,0) GENERATED ALWAYS AS (CAST(NULLIF(JSON_VALUE(`doc`,'$.amount'),'') AS DECIMAL(20,0))) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_payment_allocations` CHECK (JSON_VALID(`doc`)),
  KEY `ix_payment_id` (`payment_id`),
  KEY `ix_invoice_id` (`invoice_id`),
  KEY `ix_purchase_id` (`purchase_id`),
  KEY `ix_amount` (`amount`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `customer_returns` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `return_number` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.returnNumber'),'')) STORED,
  `customer_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.customerId'),'')) STORED,
  `invoice_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.invoiceId'),'')) STORED,
  `return_date` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.returnDate'),'')) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_customer_returns` CHECK (JSON_VALID(`doc`)),
  UNIQUE KEY `uq_return_number` (`return_number`),
  KEY `ix_customer_id` (`customer_id`),
  KEY `ix_invoice_id` (`invoice_id`),
  KEY `ix_return_date` (`return_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `customer_return_items` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `return_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.returnId'),'')) STORED,
  `product_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.productId'),'')) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_customer_return_items` CHECK (JSON_VALID(`doc`)),
  KEY `ix_return_id` (`return_id`),
  KEY `ix_product_id` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `supplier_returns` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `return_number` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.returnNumber'),'')) STORED,
  `supplier_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.supplierId'),'')) STORED,
  `purchase_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.purchaseId'),'')) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_supplier_returns` CHECK (JSON_VALID(`doc`)),
  UNIQUE KEY `uq_return_number` (`return_number`),
  KEY `ix_supplier_id` (`supplier_id`),
  KEY `ix_purchase_id` (`purchase_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `supplier_return_items` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `return_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.returnId'),'')) STORED,
  `product_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.productId'),'')) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_supplier_return_items` CHECK (JSON_VALID(`doc`)),
  KEY `ix_return_id` (`return_id`),
  KEY `ix_product_id` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `orders` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `order_number` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.orderNumber'),'')) STORED,
  `customer_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.customerId'),'')) STORED,
  `order_date` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.orderDate'),'')) STORED,
  `status` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.status'),'')) STORED,
  `kind` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.kind'),'')) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_orders` CHECK (JSON_VALID(`doc`)),
  UNIQUE KEY `uq_order_number` (`order_number`),
  KEY `ix_customer_id` (`customer_id`),
  KEY `ix_order_date` (`order_date`),
  KEY `ix_status` (`status`),
  KEY `ix_kind` (`kind`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `order_items` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `order_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.orderId'),'')) STORED,
  `product_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.productId'),'')) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_order_items` CHECK (JSON_VALID(`doc`)),
  KEY `ix_order_id` (`order_id`),
  KEY `ix_product_id` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `stock_docs` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `doc_number` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.docNumber'),'')) STORED,
  `type` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.type'),'')) STORED,
  `doc_date` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.docDate'),'')) STORED,
  `warehouse_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.warehouseId'),'')) STORED,
  `invoice_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.invoiceId'),'')) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_stock_docs` CHECK (JSON_VALID(`doc`)),
  UNIQUE KEY `uq_doc_number` (`doc_number`),
  KEY `ix_type` (`type`),
  KEY `ix_doc_date` (`doc_date`),
  KEY `ix_warehouse_id` (`warehouse_id`),
  KEY `ix_invoice_id` (`invoice_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `stock_doc_items` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `doc_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.docId'),'')) STORED,
  `product_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.productId'),'')) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_stock_doc_items` CHECK (JSON_VALID(`doc`)),
  KEY `ix_doc_id` (`doc_id`),
  KEY `ix_product_id` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `migration_backups` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `created_at` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.createdAt'),'')) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_migration_backups` CHECK (JSON_VALID(`doc`)),
  KEY `ix_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `operations` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = opId',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `entity` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.entity'),'')) STORED,
  `entity_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.entityId'),'')) STORED,
  `created_at` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.createdAt'),'')) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_operations` CHECK (JSON_VALID(`doc`)),
  KEY `ix_entity` (`entity`),
  KEY `ix_entity_id` (`entity_id`),
  KEY `ix_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `document_edits` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `entity_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.entityId'),'')) STORED,
  `updated_at` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.updatedAt'),'')) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_document_edits` CHECK (JSON_VALID(`doc`)),
  KEY `ix_entity_id` (`entity_id`),
  KEY `ix_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `supplier_products` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `supplier_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.supplierId'),'')) STORED,
  `product_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.productId'),'')) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_supplier_products` CHECK (JSON_VALID(`doc`)),
  KEY `ix_supplier_id` (`supplier_id`),
  KEY `ix_product_id` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `price_history` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `product_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.productId'),'')) STORED,
  `changed_at` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.changedAt'),'')) STORED,
  `field` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.field'),'')) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_price_history` CHECK (JSON_VALID(`doc`)),
  KEY `ix_product_id` (`product_id`),
  KEY `ix_changed_at` (`changed_at`),
  KEY `ix_field` (`field`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `price_approvals` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `product_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.productId'),'')) STORED,
  `status` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.status'),'')) STORED,
  `requested_at` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.requestedAt'),'')) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_price_approvals` CHECK (JSON_VALID(`doc`)),
  KEY `ix_product_id` (`product_id`),
  KEY `ix_status` (`status`),
  KEY `ix_requested_at` (`requested_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `cost_history` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `product_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.productId'),'')) STORED,
  `effective_date` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.effectiveDate'),'')) STORED,
  `kind` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.kind'),'')) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_cost_history` CHECK (JSON_VALID(`doc`)),
  KEY `ix_product_id` (`product_id`),
  KEY `ix_effective_date` (`effective_date`),
  KEY `ix_kind` (`kind`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `users` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `name` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.name'),'')) STORED,
  `role` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.role'),'')) STORED,
  `active` TINYINT(1) GENERATED ALWAYS AS ((JSON_VALUE(`doc`,'$.active') IN ('true','1'))) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_users` CHECK (JSON_VALID(`doc`)),
  KEY `ix_name` (`name`),
  KEY `ix_role` (`role`),
  KEY `ix_active` (`active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `salesmen` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `employee_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.employeeId'),'')) STORED,
  `active` TINYINT(1) GENERATED ALWAYS AS ((JSON_VALUE(`doc`,'$.active') IN ('true','1'))) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_salesmen` CHECK (JSON_VALID(`doc`)),
  KEY `ix_employee_id` (`employee_id`),
  KEY `ix_active` (`active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `account_adjustments` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `adjustment_number` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.adjustmentNumber'),'')) STORED,
  `customer_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.customerId'),'')) STORED,
  `adjustment_date` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.adjustmentDate'),'')) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_account_adjustments` CHECK (JSON_VALID(`doc`)),
  UNIQUE KEY `uq_adjustment_number` (`adjustment_number`),
  KEY `ix_customer_id` (`customer_id`),
  KEY `ix_adjustment_date` (`adjustment_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `expenses` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `expense_number` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.expenseNumber'),'')) STORED,
  `category` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.category'),'')) STORED,
  `expense_date` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.expenseDate'),'')) STORED,
  `paid_to` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.paidTo'),'')) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_expenses` CHECK (JSON_VALID(`doc`)),
  UNIQUE KEY `uq_expense_number` (`expense_number`),
  KEY `ix_category` (`category`),
  KEY `ix_expense_date` (`expense_date`),
  KEY `ix_paid_to` (`paid_to`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `documents` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = no',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `kind` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.kind'),'')) STORED,
  `created_at` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.createdAt'),'')) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_documents` CHECK (JSON_VALID(`doc`)),
  KEY `ix_kind` (`kind`),
  KEY `ix_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `audit_log` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `entity` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.entity'),'')) STORED,
  `entity_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.entityId'),'')) STORED,
  `created_at` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.createdAt'),'')) STORED,
  `user_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.userId'),'')) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_audit_log` CHECK (JSON_VALID(`doc`)),
  KEY `ix_entity` (`entity`),
  KEY `ix_entity_id` (`entity_id`),
  KEY `ix_created_at` (`created_at`),
  KEY `ix_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `landed_costs` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `reference_number` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.referenceNumber'),'')) STORED,
  `purchase_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.purchaseId'),'')) STORED,
  `transfer_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.transferId'),'')) STORED,
  `warehouse_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.warehouseId'),'')) STORED,
  `cost_date` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.costDate'),'')) STORED,
  `status` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.status'),'')) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_landed_costs` CHECK (JSON_VALID(`doc`)),
  UNIQUE KEY `uq_reference_number` (`reference_number`),
  KEY `ix_purchase_id` (`purchase_id`),
  KEY `ix_transfer_id` (`transfer_id`),
  KEY `ix_warehouse_id` (`warehouse_id`),
  KEY `ix_cost_date` (`cost_date`),
  KEY `ix_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `landed_cost_expenses` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `landed_cost_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.landedCostId'),'')) STORED,
  `category` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.category'),'')) STORED,
  `expense_date` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.expenseDate'),'')) STORED,
  `payment_status` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.paymentStatus'),'')) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_landed_cost_expenses` CHECK (JSON_VALID(`doc`)),
  KEY `ix_landed_cost_id` (`landed_cost_id`),
  KEY `ix_category` (`category`),
  KEY `ix_expense_date` (`expense_date`),
  KEY `ix_payment_status` (`payment_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `inventory_cost_adjust` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `landed_cost_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.landedCostId'),'')) STORED,
  `product_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.productId'),'')) STORED,
  `purchase_item_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.purchaseItemId'),'')) STORED,
  `warehouse_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.warehouseId'),'')) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_inventory_cost_adjust` CHECK (JSON_VALID(`doc`)),
  KEY `ix_landed_cost_id` (`landed_cost_id`),
  KEY `ix_product_id` (`product_id`),
  KEY `ix_purchase_item_id` (`purchase_item_id`),
  KEY `ix_warehouse_id` (`warehouse_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `employees` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `name` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.name'),'')) STORED,
  `role` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.role'),'')) STORED,
  `active` TINYINT(1) GENERATED ALWAYS AS ((JSON_VALUE(`doc`,'$.active') IN ('true','1'))) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_employees` CHECK (JSON_VALID(`doc`)),
  KEY `ix_name` (`name`),
  KEY `ix_role` (`role`),
  KEY `ix_active` (`active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `salary_payments` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `salary_number` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.salaryNumber'),'')) STORED,
  `employee_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.employeeId'),'')) STORED,
  `payment_date` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.paymentDate'),'')) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_salary_payments` CHECK (JSON_VALID(`doc`)),
  UNIQUE KEY `uq_salary_number` (`salary_number`),
  KEY `ix_employee_id` (`employee_id`),
  KEY `ix_payment_date` (`payment_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `milling_jobs` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `job_number` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.jobNumber'),'')) STORED,
  `mill_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.millId'),'')) STORED,
  `job_date` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.jobDate'),'')) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_milling_jobs` CHECK (JSON_VALID(`doc`)),
  UNIQUE KEY `uq_job_number` (`job_number`),
  KEY `ix_mill_id` (`mill_id`),
  KEY `ix_job_date` (`job_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `milling_job_items` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = id',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `job_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.jobId'),'')) STORED,
  `product_id` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.productId'),'')) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_milling_job_items` CHECK (JSON_VALID(`doc`)),
  KEY `ix_job_id` (`job_id`),
  KEY `ix_product_id` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sync_queue` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = opId',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `state` VARCHAR(191) GENERATED ALWAYS AS (NULLIF(JSON_VALUE(`doc`,'$.state'),'')) STORED,
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_sync_queue` CHECK (JSON_VALID(`doc`)),
  KEY `ix_state` (`state`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `legacy` (
  `pk` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_nopad_bin NOT NULL COMMENT 'record key = k',
  `doc` LONGTEXT NOT NULL,
  `rev` INT UNSIGNED NOT NULL DEFAULT 1,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`pk`),
  CONSTRAINT `doc_is_json_legacy` CHECK (JSON_VALID(`doc`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `data_version` (
  `id` TINYINT UNSIGNED NOT NULL,
  `v` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `row_updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT IGNORE INTO `data_version` (`id`, `v`) VALUES (1, 0);
